# coding: utf-8
"""
Loader for MOL files (generated by MolView.org)

Option:
  filename  Name of the mol file.
"""

import numpy as np
#All-atom THF model

from logging import getLogger
import genice2.molecules

class Molecule(genice2.molecules.Molecule):
    """
Loader for MOL files (generated by MolView.org)

    Option:
      file=name  Name of the mol file.
    """
    def __init__(self, **kwargs):
        logger = getLogger()
        for k, v in kwargs.items():
            if v == True:
                filename = k
            elif k=="file":
                filename = v
        sites = []
        atoms = []
        with open(filename) as file:
            molname = file.readline().strip()
            file.readline()
            file.readline()
            line = file.readline()
            cols = line.split()
            natom = int(cols[0])
            for i in range(natom):
                line = file.readline()
                cols = line.split()
                sites.append([float(x) for x in cols[:3]])
                atoms.append(cols[3])
        self.sites  = np.array(sites)
        self.labels = atoms
        self.name   = molname
