# coding: utf-8
"""
XMol file format (.xyz)
"""

from io import TextIOWrapper
import sys

from genice2.decorators import timeit, banner
import genice2.formats
from genice2.molecules import serialize
from genice2.genice import GenIce


class Format(genice2.formats.Format):
    """
    The atomic positions of the molecules are output in a crude XYZ format.
    No options available.
    """

    def __init__(self, **kwargs):
        pass

    @timeit
    @banner
    def dump(self, genice: GenIce, file: TextIOWrapper):
        "Output in XYZ format."
        atoms = []
        for mols in genice.full_atomic_positions():
            atoms += serialize(mols)

        s = ""
        s += "{0}\n".format(len(atoms))
        s += "Generated by GenIce. https://github.com/vitroid/GenIce\n"
        for atom in atoms:
            molorder, resname, atomname, position, order = atom
            s += f"{atomname:5} {position[0] * 10:9.4f} {position[1] * 10:9.4f} {position[2] * 10:9.4f}\n"
        s = "#" + "\n#Command line: " + " ".join(sys.argv) + "\n" + s
        file.write(s)
