# coding: utf-8
import logging

import numpy as np

from genice import rigid
from genice import formatter

class Formatter(formatter.Formatter):
    """
    XMol file format (.xyz)
    """
    def __init__(self):
        self.hooks[7] = self.hook7

        
    def hook7(self, lattice):
        logger = logging.getLogger()
        logger.info("Total number of atoms: {0}".format(len(lattice.atoms)))
        logger.info("Output in MDView format.")
        s = ""
        s += "{0}\n".format(len(lattice.atoms))
        s += "Generated by GenIce. https://github.com/vitroid/GenIce\n"
        for i in range(len(lattice.atoms)):
            molorder, resname, atomname, position = lattice.atoms[i]
            s += "{0:5} {1:9.4f} {2:9.4f} {3:9.4f}\n".format(atomname,position[0]*10,position[1]*10,position[2]*10)
        s = '#' + "\n#".join(lattice.doc) + "\n" + s
        print(s,end="")
