BASE=../..
GENICE=$(BASE)/genice.x
ANALICE=$(BASE)/analice.x --debug
LIB=$(BASE)/genice2
FMT=$(LIB)/formats
LTC=$(LIB)/lattices
LDR=$(LIB)/loaders
UTIL=.
REFD=ref
.DELETE_ON_ERROR:

include Makefile.rules
