# -*- makefile -*-
all: test1.done   test2.done   test3.done   test4.done   test_2d.gro
all: test_3.ar3a  test_4.ngph  test_5.nx3a  test_6.gro   test_7.mdv
all: test_12.scad test_16.py   test_17.nx4a test_1c.ar3r test_CS1.cif
all: test_CS2.cif test_HS1.xyz test_TS1.yap test_2dL.gro test_7.mdva
#all: test19.done
all: test_1hreshape.py test_2D3.ringtest test_prism7.ringtest
all: test_3xFAU.yap
all: test_T.pov
all: test_7.re.gro
# all: test_MTN.gro test_MTN.re.gro
# all: test_ITT.gro
all: test_7.analice.yap
all: test_2D3.analice.yap
all: test_gro2.gro


test1.done: $(FMT)/gromacs.py
	$(GENICE) test1 --guest 12=g12 --rep 1 1 1 --debug > /dev/null
	touch test1.done
test2.done: $(FMT)/gromacs.py
	$(GENICE) test2 --guest 12=g12 --rep 1 1 1 --debug > /dev/null
	touch test2.done
test3.done: $(FMT)/gromacs.py
	$(GENICE) test3 --guest 12=g12 --rep 1 1 1 --debug > /dev/null
	touch test3.done
test4.done: $(FMT)/gromacs.py
	$(GENICE) test4 --guest 12=g12 --rep 1 1 1 --debug > /dev/null
	touch test4.done
test_2d.gro: $(FMT)/gromacs.py
	$(GENICE) 2d --rep 2 2 3 | fgrep -v "Command line:" > $@                                   ;diff $(REFD)/$@ $@
test_3.ar3a: $(FMT)/com.py
	$(GENICE) 3  --rep 2 2 3 --format c | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_4.ngph: $(FMT)/digraph.py
	$(GENICE) 4  --rep 2 2 3 --format d | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_5.nx3a:  $(FMT)/euler.py
	$(GENICE) 5  --rep 2 2 3 --format e | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_6.gro: $(FMT)/gromacs.py
	$(GENICE) 6  --rep 2 2 4 --format g | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_7.mdv: $(FMT)/mdview.py
	$(GENICE) 7  --rep 2 2 4 --format m | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_7.mdva: $(FMT)/mdv_au.py
	$(GENICE) 7  --rep 2 2 4 --format mdv_au | fgrep -v "Command line:" > $@                   ;diff $(REFD)/$@ $@
test_12.scad: $(FMT)/openscad.py
	$(GENICE) 12 --rep 2 2 3 --format o | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_16.py: $(FMT)/python.py
	$(GENICE) 16 --rep 1 1 2 --format p | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_17.nx4a: $(FMT)/quaternion.py
	$(GENICE) 17 --rep 1 1 2 --format q | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_1c.ar3r: $(FMT)/rcom.py
	$(GENICE) 1c --rep 1 1 2 --format r | fgrep -v "Command line:" > $@                        ;diff $(REFD)/$@ $@
test_CS1.cif: $(FMT)/cif.py
	$(GENICE) CS1 --guest 14=g14*0.5 -G 0=me --rep 1 1 2 --format cif | fgrep -v "Command line:" > $@ ;diff $(REFD)/$@ $@
test_CS2.cif: $(FMT)/cif2.py
	$(GENICE) CS2 --nodep -c 0=Na -a 1=Cl --rep 1 1 2 --format cif2 | fgrep -v "Command line:" > $@  ;$(UTIL)/cifdiff.sh $(REFD)/$@ $@
test_HS1.xyz: $(FMT)/xyz.py
#test for spot semiclathrate (TBAB)
	$(GENICE) HS1 --nodep -c 3=N -a 1=Br -H 11=Bu-:3 -H 23=Bu-:3 -H 13=Bu-:3 -H 7=Bu-:3 --rep 1 1 2 --format xyz | fgrep -v "Command line:" > $@; diff $(REFD)/$@ $@
test_TS1.yap: $(FMT)/yaplot.py
	$(GENICE) TS1 --guest 12=g12 --rep 1 1 2 --format yaplot | fgrep -v "Command line:" > $@ ;diff $(REFD)/$@ $@
test_T.pov: $(FMT)/povray.py
	$(GENICE) T --guest 12=g12 --rep 1 1 1 --format povray | fgrep -v "Command line:" > $@   ;diff $(REFD)/$@ $@
test_2dL.gro: $(FMT)/gromacs.py
	$(GENICE) 2d --rep 8 8 8 | fgrep -v "Command line:" > $@
test_1hreshape.py: $(FMT)/reshape.py
	$(GENICE) 1h --rep 1 1 1 --format reshape[1,1,-2,1,-1,0,1,1,1] | fgrep -v "Command line:" > $@ ;diff $(REFD)/$@ $@
test_2D3.ringtest: $(FMT)/_ring.py
	$(GENICE) 2D3 --rep 5 5 1 --format _ring | fgrep -v "Command line:" > $@                ;diff $(REFD)/$@ $@
test_prism7.ringtest: $(FMT)/_ring.py
	$(GENICE) prism[7] --rep 1 1 1 --format _ring | fgrep -v "Command line:" > $@           ;diff $(REFD)/$@ $@
test_3xFAU.yap: $(FMT)/yaplot.py
	$(GENICE) xFAU[3] --rep 1 1 1 --format yaplot | fgrep -v "Command line:" > $@           ;diff $(REFD)/$@ $@
test_7.gro: $(FMT)/gromacs.py
	$(GENICE) 7 -r 2 2 2 | fgrep -v "Command line:" > $@
test_7.re.gro: test_7.gro $(FMT)/gromacs.py
	$(ANALICE) $< -O O -H H --rep 1 1 1 --asis  | fgrep -v "Command line:" > $@           ;diff $(REFD)/$@ $@
	-$(ANALICE) $< -O O  --rep 1 1 1 | fgrep -v "Command line:" > $@ # should fail
	echo It must fail because the molecular orientations are missing.  Ice 7 is so crowded structure that its HB network cannot be estimated solely from Oxygen positions.
# test_MTN.gro: $(LTC)/zeolite.py $(FMT)/gromacs.py
# 	$(GENICE) zeolite[MTN] --rep 1 1 1 | fgrep -v "Command line:" > $@
# test_MTN.re.gro: MTN.cif $(LTC)/cif.py $(FMT)/gromacs.py
# 	$(GENICE) cif[MTN.cif] --rep 1 1 1 | fgrep -v "Command line:" > $@                     ;diff $(REFD)/$@ $@
# test_ITT.gro: $(LTC)/zeolite.py $(FMT)/gromacs.py
# 	$(GENICE) zeolite[ITT] --rep 1 1 1 | fgrep -v "Command line:" > $@                     ;diff $(REFD)/$@ $@
test_7.analice.yap: test_7.gro $(FMT)/yaplot.py
	$(ANALICE) $< -f yaplot | fgrep -v "Command line:" > $@                           #     ;diff $(REFD)/$@ $@
test_2D3.gro: $(FMT)/gromacs.py
	$(GENICE) 2D3 -r 4 4 1 | fgrep -v "Command line:" > $@
test_2D3.analice.yap: test_2D3.gro $(FMT)/yaplot.py
	$(ANALICE) $< -f yaplot | fgrep -v "Command line:" > $@                          #      ;diff $(REFD)/$@ $@
test_gro2.gro:
	$(ANALICE) %05d-0.gro --filerange 5:10 --framerange 0:9999:3 -O Ow -H Hw > $@
