from logging import getLogger
from io import TextIOWrapper
import numpy as np
from typing import Dict, List
from genice3.molecule import Molecule
from genice3.genice import GenIce3, ConfigurationError, ShowUsageError, GuestSpec
from genice3.plugin import safe_import


def to_gro(
    cellmat: np.ndarray,
    waters: Dict[int, Molecule],
    guests: List[Molecule],
    ions: Dict[int, Molecule],
    command_line: str = None,
) -> str:
    """Output in Gromacs format.

    parametersには、hooksで指定したstageの結果が含まれる。
    """
    logger = getLogger("to_gro")
    logger.info("Generating .gro...")

    if not (cellmat[0, 1] == 0 and cellmat[0, 2] == 0 and cellmat[1, 2] == 0):
        logger.info(
            "  The specified reshaping matrix does not obey the requirements for Gromacs' unit cell convention."
        )
        a = np.linalg.norm(cellmat[0])
        b = np.linalg.norm(cellmat[1])
        c = np.linalg.norm(cellmat[2])
        ea = cellmat[0] / a
        eb = cellmat[1] / b
        ec = cellmat[2] / c
        A = np.degrees(np.arccos(eb @ ec))
        B = np.degrees(np.arccos(ec @ ea))
        C = np.degrees(np.arccos(ea @ eb))
        rotmat = np.linalg.inv(cellmat) @ cellvectors(a, b, c, A, B, C)
        logger.info("  The reshape matrix is reoriented.")
    else:
        rotmat = np.eye(3)

    atoms = []
    residue_count = 1
    for water in waters.values():
        for name, position in zip(water.labels, water.sites):
            atoms.append([residue_count, water.name, name, position])
        residue_count += 1
    for guest in guests:
        for name, position in zip(guest.labels, guest.sites):
            atoms.append([residue_count, guest.name, name, position])
        residue_count += 1
    for ion in ions.values():
        for name, position in zip(ion.labels, ion.sites):
            atoms.append([residue_count, ion.name, name, position])
        residue_count += 1

    logger.info("  Total number of atoms: {0}".format(len(atoms)))
    if len(atoms) > 99999:
        logger.warn(
            "  Fixed-digit format of Gromacs cannot deal with atoms more than 99999. Residue number and atom number are set appropriately."
        )
    s = ""
    if command_line:
        s += f"{command_line} # "
    s += "Generated by GenIce https://github.com/vitroid/GenIce \n"
    s += "{0}\n".format(len(atoms))
    molorder = 0
    for i, atom in enumerate(atoms):
        resno, resname, atomname, position = atom
        position = position @ rotmat
        if resno == 0:
            molorder += 1
        if len(atoms) > 99999:
            s += f"{9999:5d}{resname:5s}{atomname:>5s}{9999:5d}{position[0]:8.3f}{position[1]:8.3f}{position[2]:8.3f}\n"
        else:
            s += f"{molorder:5d}{resname:5s}{atomname:>5s}{i + 1:5d}{position[0]:8.3f}{position[1]:8.3f}{position[2]:8.3f}\n"
    cellmat = cellmat @ rotmat
    if cellmat[1, 0] == 0 and cellmat[2, 0] == 0 and cellmat[2, 1] == 0:
        s += "    {0:.8f} {1:.8f} {2:.8f}\n".format(
            cellmat[0, 0], cellmat[1, 1], cellmat[2, 2]
        )
    else:
        s += "    {0:.8f} {1:.8f} {2:.8f} {3:.8f} {4:.8f} {5:.8f} {6:.8f} {7:.8f} {8:.8f}\n".format(
            cellmat[0, 0],
            cellmat[1, 1],
            cellmat[2, 2],
            cellmat[0, 1],
            cellmat[0, 2],
            cellmat[1, 0],
            cellmat[1, 2],
            cellmat[2, 0],
            cellmat[2, 1],
        )
    return s


def guest_processor(arg: dict):
    # 辞書のvaluesの特殊記法をparseする。
    logger = getLogger("guest_processor")
    logger.info(f"{arg=}")
    result = {}
    for cage, guest_specs in arg.items():
        logger.info(f"{cage=} {guest_specs=}")
        result[cage] = []
        total_occupancy = 0
        for guest_spec in guest_specs.split("+"):
            if "*" in guest_spec:
                occupancy, molecule = guest_spec.split("*")
                occupancy = float(occupancy)
            else:
                molecule = guest_spec
                occupancy = 1.0
            # moleculeはオプションを含んでいるかもしれないが、今は処理しない。
            molecule = safe_import("molecule", molecule).Molecule()
            result[cage].append(GuestSpec(molecule, occupancy))
            total_occupancy += occupancy
        if total_occupancy > 1.0:
            raise ConfigurationError(f"Total occupancy of {option} is greater than 1.0")
    logger.debug(f"{result=}")
    return result


def spot_guest_processor(arg: dict) -> Dict[int, Molecule]:
    # keyとvalueを変換するのみ
    result: Dict[int, Molecule] = {}
    for label, molecule in arg.items():
        if label == "?":
            raise ShowUsageError(
                "Use '?' to display cage information. "
                "This option triggers a survey of cage positions and types."
            )
        result[int(label)] = safe_import("molecule", molecule).Molecule()
    return result


def water_model_processor(arg: str) -> Molecule:
    # オプション文字列は今のところないのでこれで動く。
    return safe_import("molecule", arg).Molecule()


# 水分子モデルもguestもdumpでしか必要としないので、gromacsの属性ではないか?
# デコレータは不要：safe_importが自動的に適用する


def dump(genice: GenIce3, file: TextIOWrapper, **options):
    """
    Gromacs形式で出力

    Args:
        genice: GenIce3インスタンス
        file: 出力先ファイル
        options: プラグインオプション
            - safe_importにより自動的に辞書にパースされる
            - プラグイン側では既に辞書形式になっている
    """
    logger = getLogger("gromacs.dump")
    # 設定可能なオプションはguestとspot_guest。
    guest_info = guest_processor(options.get("guest", {}))
    spot_guest_info = spot_guest_processor(options.get("spot_guest", {}))
    water_model = water_model_processor(options.get("water_model", "4site"))
    # water = FourSiteWater()  # dummy

    waters = genice.water_molecules(water_model=water_model)
    guests = genice.guest_molecules(guests=guest_info, spot_guests=spot_guest_info)
    ions = genice.substitutional_ions()

    command_line = options.get("command_line").rstrip()
    output = to_gro(
        cellmat=genice.cell,
        waters=waters,
        guests=guests,
        ions=ions,
        command_line=command_line,
    )
    file.write(output)
